general.import = ["~/.config/alacritty/themes/themes/hyper.toml"]

general.live_config_reload = true
[colors]
draw_bold_text_with_bright_colors = true


[cursor]
style = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 13.0

[font.bold]
family = "Hack NerdFont"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Hack NerdFont"
style = "Italic"

[font.normal]
family = "JetBrains Mono NerdFont"
style = "Medium"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Shift"


[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"


[scrolling]
history = 10000
multiplier = 2

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"


[window]
decorations = "Buttonless"
opacity = 0.80

[window.dimensions]
columns = 80
lines = 24

[window.padding]
x = 2
y = 0
